boardgame_project: # name of the profile described on dbt_project.yml
  outputs:
    dev:
      account: JSA18243
      database: BOARDGAME
      password: dbtPassword123
      role: transform
      schema: dbt_lpal # dbt_[first-initial-last-name] (ex: dbt_fbalseiro)
      threads: 4
      type: snowflake
      user: dbt
      warehouse: DBT_CERTIFICATION_PROJECT_WH
  target: dev